config/routes.rb
Rails.application.routes.draw do
  resources :languages
  resources :books do
    resources :book_zips, only: [:new, :create]
  end

  resources :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get "/epub_books", to: "epub_books#index"
  root "epub_books#index"

  resources :book_zips, only: [:index, :show, :destroy] do
    post 'export', on: :collection
    resources :chapter_zips, only:
      [:new, :create, :edit, :update, :destroy] do
      member do
        get :change_paragraph_ranges
        post :update_ranges
      end
    end

  end

  resources :epub_books do
    resources :epub_items, only: [:show, :edit, :update]
    resources :chapters, only: [:index, :show, :update]
    member do
      post :create_chapters
      post :update_ignored_paragraphs
      get :filter_paragraphs
    end
  end
end

app/models/epub_book.rb
class EpubBook < ApplicationRecord
  # TODO add parsing options validation
  serialize :title_xpaths, Array
  has_many :epub_items,
    -> { order('position') },
    dependent: :destroy
  has_many :book_zips_source, inverse_of: :ebook_source,
    class_name: "BookZip", foreign_key: :ebook_source_id,
    dependent: :destroy
  has_many :book_zips_target, inverse_of: :ebook_target,
    class_name: "BookZip", foreign_key: :ebook_target_id,
    dependent: :destroy
  has_many :chapters,
    -> { order('chapters.position') },
    dependent: :destroy
  has_many :paragraphs,
    -> {order 'chapters.position, paragraphs.position'},
    through: :chapters
  belongs_to :book
  belongs_to :language

  def file=(file)
    self.filename = file.original_filename
    book = GEPUB::Book.parse(file.tempfile)
    self.epub_items = book.spine.itemref_list.map.with_index do |id_ref, idx|
      name = id_ref['idref']
      item = book.items[name]
      if item.media_type == 'application/xhtml+xml'
        EpubItem.new(epub_book: self,
                     position: idx,
                     name: name,
                     content: item.content
                    )
      end
    end.compact
  end

  def matching_tag_position(tag)
    title_conditions.each_with_index do |tc, i|
      class_match = !tc[:class] || (
        tag.attributes['class'] && tag.attributes['class'].value == tc[:class]
      )
      node_text = tag.text.strip
      start_match = !tc[:start] || node_text.starts_with?(tc[:start]
      )
      if (tag.name == tc[:tag]) && class_match && start_match
        return i
      end
    end
    return
  end

  def title
    "#{book.title} (#{language.name})"
  end

  def title_xpaths_text=(v)
    self.title_xpaths = v.split(';')
  end

  def title_xpaths_text
    title_xpaths.join(';')
  end

  def store_structured
    current_title = Hash.new('')
    current_content = [['', []]]
    items = epub_items.where('position >= ? AND position <= ?',
                             start_position, end_position)
    items.each do |item|
      item.parse_content(current_title, current_content)
    end
    transaction do
      chapters.destroy_all
      current_content.each_with_index do |t_ps, i0|
        c = chapters.build(title: t_ps[0], position: i0)
        t_ps[1].each_with_index do |par_content, i1|
          c.paragraphs.build(position: i1, content: par_content, chapter: c)
        end
        if c.paragraphs.present?
          c.save
        end
      end
    end
  end
end

app/controllers/epub_books_controller.rb
class EpubBooksController < ApplicationController
  def index
    @epub_books = EpubBook.all
  end

  def new
    @epub_book = EpubBook.new
  end

  def create
    @epub_book = EpubBook.new(book_params)
    if @epub_book.save
      redirect_to @epub_book
    else
      render :new
    end
  end

  def show
    @epub_book = EpubBook.find(params[:id])
  end

  def edit
    @epub_book = EpubBook.find(params[:id])
  end

  def filter_paragraphs
    @epub_book = EpubBook.find(params[:id])
    if params.include? 'paragraph_search'
      @search = paragraph_search_params
    else
      @search = {}
    end
    if @search
      @paragraphs = @epub_book.paragraphs
      if @search['not_ignored']
        @paragraphs = @paragraphs.where(ignore: false)
      end
      if @search['ignored']
        @paragraphs = @paragraphs.where(ignore: true)
      end
      if @search['has_no_words']
        @paragraphs = @paragraphs.filter{|p| p.content.split.size == 0}
      end
      if @search['regexp'].present?
        r = Regexp.new @search['regexp']
        @paragraphs = @paragraphs.filter{|p| p.content.match r}
      end
      @paragraphs = @paragraphs[..200]
    else
      @paragraphs = []
    end
  end

  def update_ignored_paragraphs
    @epub_book = EpubBook.find(params[:id])
    p = ignore_paragraphs_params
    if p[:ignore_all_paragraphs]
      @epub_book.paragraphs.where(
        'paragraphs.id IN (?)', p[:current_paragraphs_ids]
      ).update_all(ignore: true)
    else
      @epub_book.paragraphs.where(
        'paragraphs.id IN (?)', p[:ignored_paragraphs_ids]
      ).update_all(ignore: true)
      @epub_book.paragraphs.where(
        'paragraphs.id IN (?) and paragraphs.id NOT IN (?)',
        p[:current_paragraphs_ids], p[:ignored_paragraphs_ids]
      ).update_all(ignore: false)
    end
    redirect_back(fallback_location: root_path)
  end

  def update
    @epub_book = EpubBook.find(params[:id])
    if @epub_book.update(book_params)
      redirect_to @epub_book
    else
      render :edit
    end
  end

  def destroy
    @epub_book = EpubBook.find(params[:id])
    @epub_book.destroy

    redirect_to epub_books_path
  end

  def create_chapters
    @epub_book = EpubBook.find(params[:id])
    @epub_book.store_structured
    redirect_to epub_book_chapters_path(@epub_book)
  end

  private

  def ignore_paragraphs_params
    params.permit(
      :ignore_all_paragraphs,
      current_paragraphs_ids: [],
      ignored_paragraphs_ids: []
    )
  end

  def paragraph_search_params
    params.require(:paragraph_search).permit(
      :regexp, :not_ignored, :ignored, :has_no_words
     )
  end

  def book_params
    params.require(:epub_book).permit(
      :file, :content_location, :title_xpaths_text, :content_xpath,
      :excluded_content_tag, :start_position, :end_position, :book_id,
      :language_id, :custom_update_title
     )
  end
end

app/helpers/epub_books_helper.rb
module EpubBooksHelper
  def custom_update_title_options
    [["", ""]] + CustomTitleProcessing.public_instance_methods.map{|m| [m,m]}
  end
end

app/views/epub_books/edit.html.erb
<h1> Edit Epub book</h1>

<%= form_with model: @epub_book do |form| %>
  <div class="field">
    <%= form.label :book %>
    <%= form.collection_select :book_id, Book.all, :id, :title %>
  </div>
  <div class="field">
    <%= form.label :language %>
    <%= form.collection_select :language_id, Language.all, :id, :name %>
  </div>
  <div class="field">
    <%= form.label :content_location %>
    <%= form.text_field :content_location %>
  </div>
  <div class="field">
    <%= form.label :title_xpaths %>
    <%= form.text_field :title_xpaths_text %>
  </div>
  <div class="field">
    <%= form.label :custom_update_title %>
    <%= form.select :custom_update_title, custom_update_title_options %>
  </div>

  <div class="field">
    <%= form.label :content_xpath %>
    <%= form.text_field :content_xpath %>
  </div>
  <div class="field">
    <%= form.label :excluded_content_tag %>
    <%= form.text_field :excluded_content_tag %>
  </div>
  <div class="field">
    <%= form.label :start_position %>
    <%= form.number_field :start_position %>
  </div>
  <div class="field">
    <%= form.label :end_position %>
    <%= form.number_field :end_position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/epub_books/filter_paragraphs.html.erb
<h2> Ignored paragraphs search</h2>
<div>
<%= form_with url: filter_paragraphs_epub_book_path(@epub_book), method: :get do |form| %>
  <div class="field">
    <%= form.label "Search regexp:" %>
    <%= form.text_field 'paragraph_search[regexp]', value: @search['regexp'] %>
  </div>
  <div class="field">
    <%= form.label "Not ignored" %>
    <%= check_box_tag 'paragraph_search[not_ignored]', '1',  @search['not_ignored'] %>
  </div>
  <div class="field">
    <%= form.label "Ignored" %>
    <%= check_box_tag 'paragraph_search[ignored]', '1',  @search['ignored'] %>
  </div>
  <div class="field">
    <%= form.label "Has no words" %>
    <%= check_box_tag 'paragraph_search[has_no_words]', '1', @search['has_no_words']%>
  </div>
  <div class="actions">
    <%= form.submit "Search" %>
  </div>
<% end %>
</div>
<div>
<%= form_with url: update_ignored_paragraphs_epub_book_path(@epub_book), method: :post do |form| %>
  <%= form.submit 'Ignore all!', name: 'ignore_all_paragraphs'%>
  <table>
  <tr> <th> Ignored? </th><th> Content </th> </tr>
  <% @paragraphs.each do |p| %>
    <tr>
      <td>
        <div class="field">
          <%= hidden_field_tag 'current_paragraphs_ids[]', p.id %>
          <%= check_box_tag 'ignored_paragraphs_ids[]', p.id, p.ignore %>
        </div>
      </td>
      <td>
        <%= p.content %>
      </td>
    <tr>
  <% end %>
  </table>
  <%= form.submit 'Update' %>
<% end %>
</div>

app/views/epub_books/index.html.erb
<h1>Epub books</h1>
<p> <%= link_to "New book", new_epub_book_path %>
</p>

<ul>
  <% @epub_books.each do |epub_book| %>
    <li>
      <%= link_to epub_book.title, epub_book_path(epub_book) %>
      (<%= epub_book.filename %>)
      <%= link_to "Edit", edit_epub_book_path(epub_book) %>
      <%= link_to "Destroy", epub_book_path(epub_book),
        data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?" } %>
      <%= epub_book.chapters.count %> chapters
    </li>
  <% end %>
</ul>

app/views/epub_books/new.html.erb
<h1> New Epub book </h1>

<%= form_with model: @epub_book do |form| %>
  <div class="field">
    <%= form.label :book %>
    <%= form.collection_select :book_id, Book.all, :id, :title %>
  </div>
  <div class="field">
    <%= form.label :language %>
    <%= form.collection_select :language_id, Language.all, :id, :name %>
  </div>
  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/epub_books/show.html.erb
<h1>Epub book</h1>
<p><%= @epub_book.title %>
<%= link_to "Edit", edit_epub_book_path(@epub_book) %>
<%= link_to ("Chapters (" + @epub_book.chapters.count.to_s + ")"),
  epub_book_chapters_path(@epub_book) %>
<%= link_to "Ignored paragraphs", filter_paragraphs_epub_book_path(@epub_book) %>
<%= link_to "Destroy", epub_book_path(@epub_book),
  data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %>
<%= button_to "Create chapters", create_chapters_epub_book_path(@epub_book)%>
</p>

<p> Parsing options:
<ul>
  <li>Content location: <%= @epub_book.content_location %> </li>
  <li>Title xpaths: <%= @epub_book.title_xpaths_text %> </li>
  <li>Content xpath: <%= @epub_book.content_xpath %> </li>
  <li>Custom update title: <%= @epub_book.custom_update_title %> </li>
  <li>Excluded content tag: <%= @epub_book.excluded_content_tag %> </li>
  <li>Start position: <%= @epub_book.start_position %> </li>
  <li>End position: <%= @epub_book.end_position %> </li>
</ul>
</p>

Epub items:

<ul>
  <% @epub_book.epub_items.each do |epub_item| %>
    <li>
      <%= epub_item.position %> -
      <%= link_to epub_item.name, epub_book_epub_item_path(@epub_book, epub_item) %>
      (<%= epub_item.body_text[..250] + '...' %>)
    </li>
  <% end %>
</ul>