config/routes.rb
Rails.application.routes.draw do
  resources :languages
  resources :books do
    resources :book_zips, only: [:new, :create]
  end

  resources :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get "/epub_books", to: "epub_books#index"
  root "epub_books#index"

  resources :book_zips, only: [:index, :show, :destroy] do
    post 'export', on: :collection
    resources :chapter_zips, only:
      [:new, :create, :edit, :update, :destroy] do
      member do
        get :change_paragraph_ranges
        post :update_ranges
      end
    end

  end

  resources :epub_books do
    resources :epub_items, only: [:show, :edit, :update]
    resources :chapters, only: [:index, :show, :update]
    member do
      post :create_chapters
      post :update_ignored_paragraphs
      get :filter_paragraphs
    end
  end
end

app/models/book_zip.rb
class BookZip < ApplicationRecord
  belongs_to :ebook_source, class_name: "EpubBook"
  belongs_to :ebook_target, class_name: "EpubBook"
  has_many :chapter_zips,
    -> { order('position') },
     dependent: :destroy

  def title
    "#{ebook_source.book.title} (#{ebook_source.language.name} - #{ebook_target.language.name})"
  end

  def title_with_author
    "#{ebook_source.book.author.name} - #{title}"
  end

  def chapter_zips_with_extra_includes
    chapter_zips.includes(
      source_chapter: :epub_book,
      target_chapter: :epub_book
    )
  end

  def export_hash
    chapters = chapter_zips.map do |cz|
      paragraphs = cz.paragraph_matches.map do |pm|
        {
          source_paragraphs: pm.source_paragraphs.map do |p|
            {
              content: p.content,
              ignored: cz.zip_info['ignored_source_ids'].include?(p.id)
            }
          end,
          target_paragraphs: pm.target_paragraphs.map do |p|
            {
              content: p.content,
              ignored: cz.zip_info['ignored_target_ids'].include?(p.id)
            }
          end
        }
      end
      {
        source_title: cz.source_chapter.title,
        target_title: cz.target_chapter.title,
        paragraphs: paragraphs
      }
    end
    {
      title: ebook_source.book.title,
      author: ebook_source.book.author.name,
      source_language: ebook_source.language.name,
      target_language: ebook_target.language.name,
      chapters: chapters
    }
  end
end

app/controllers/book_zips_controller.rb
class BookZipsController < ApplicationController
  before_action :set_book_zip, only: %i[ show destroy ]

  def index
    @book_zips = BookZip.all
  end

  def new
    @book = Book.find(params[:book_id])
    @book_zip = BookZip.new
  end

  def export
    bz_ids = export_book_zips_params[:book_zips_ids]
    stringio = Zip::OutputStream.write_buffer do |stream|
      bz_ids.each do |bz_id|
        book_zip = BookZip.find(bz_id)
        f_name = book_zip.title
        author = book_zip.ebook_source.book.author.name

        stream.put_next_entry("#{author}/#{f_name}.json")
        stream.write JSON.dump(book_zip.export_hash)
      end
    end
    send_data(
      stringio.string,
      :filename => "book_zips.zip",
      :type => 'application/zip'
    )
  end

  def create
    @book = Book.find(params[:book_id])
    @book_zip = BookZip.new(book_zip_params)
    if @book_zip.save
      redirect_to @book_zip
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @book_zip.destroy

    respond_to do |format|
      format.html { redirect_to book_zips_url, notice: "Book zip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_book_zip
    @book_zip = BookZip.find(params[:id])
  end

  def book_zip_params
    params.require(:book_zip).permit(
      :ebook_source_id, :ebook_target_id
     )
  end

  def export_book_zips_params
    params.permit(
      book_zips_ids: []
    )
  end
end

app/helpers/book_zips_helper.rb
module BookZipsHelper
end

app/views/book_zips/index.html.erb
<h1>Book zips</h1>
<%= form_with url: export_book_zips_path,
  method: :post,
  data: {turbo: false} do |form| %>
  <ul class="book_zips">
    <% @book_zips.each do |book_zip| %>
      <li>
        <%= check_box_tag 'book_zips_ids[]', book_zip.id, true %>
        <%= link_to book_zip.title_with_author, book_zip_path(book_zip) %>
        <%= link_to 'Destroy', book_zip, data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?" } %>
      </li>
    <% end %>
  </ul>
  <div class="actions">
    <%= form.submit "Export" %>
  </div>
<% end %>

app/views/book_zips/new.html.erb
<h1> New book zip </h1>

<%= form_with model: [@book, @book_zip] do |form| %>
  <div class="field">
    <%= form.label :ebook_source %>
    <%= form.collection_select :ebook_source_id, @book.epub_books, :id, :title  %>
  </div>

  <div class="field">
    <%= form.label :ebook_target %>
    <%= form.collection_select :ebook_target_id, @book.epub_books, :id, :title  %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_zips/show.html.erb
<h1> Book zip </h1>
<p><%= @book_zip.ebook_source.title %> + <%= @book_zip.ebook_target.title %>
</p>
<%= link_to "New chapter", new_book_zip_chapter_zip_path(@book_zip) %>

<p> Chapter zips:
<ul>
  <% @book_zip.chapter_zips_with_extra_includes.each do |chapter_zip| %>
    <li>
      <%= chapter_zip.position %>.
      <%= link_to (chapter_zip.source_chapter.title +
             ("(#{chapter_zip.start_position_source}-#{chapter_zip.end_position_source}/#{chapter_zip.source_chapter.max_p_position})")),
      epub_book_chapter_path(chapter_zip.source_chapter.epub_book, chapter_zip.source_chapter) %> -
      <%= link_to (chapter_zip.target_chapter.title +
               ("(#{chapter_zip.start_position_target}-#{chapter_zip.end_position_target}/#{chapter_zip.target_chapter.max_p_position})")),
      epub_book_chapter_path(chapter_zip.target_chapter.epub_book, chapter_zip.target_chapter) %>
    <%= link_to '(Edit)',
      edit_book_zip_chapter_zip_path(@book_zip, chapter_zip),
      data: {turbo: false}
    %>
      <%= link_to "Destroy", book_zip_chapter_zip_path(@book_zip, chapter_zip),
                  data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>
</p>