config/routes.rb
Rails.application.routes.draw do
  resources :languages
  resources :books do
    resources :book_zips, only: [:new, :create]
  end

  resources :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get "/epub_books", to: "epub_books#index"
  root "epub_books#index"

  resources :book_zips, only: [:index, :show, :destroy] do
    post 'export', on: :collection
    resources :chapter_zips, only:
      [:new, :create, :edit, :update, :destroy] do
      member do
        get :change_paragraph_ranges
        post :update_ranges
      end
    end

  end

  resources :epub_books do
    resources :epub_items, only: [:show, :edit, :update]
    resources :chapters, only: [:index, :show, :update]
    member do
      post :create_chapters
      post :update_ignored_paragraphs
      get :filter_paragraphs
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookZipper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= yield(:head) %>
  </head>

  <body>
    <div class='navbar'>
    <%= link_to "Epub books", epub_books_path %>
    <%= link_to "Book zips", book_zips_path %>
    <%= link_to "Books", books_path %>
    <%= link_to "Authors", authors_path %>
    <%= link_to "Languages", languages_path %>
    </div>
    <%= yield %>
  </body>
</html>